### ISSUE TITLE
hi, about the evaluation criteria!

### ISSUE THREAD

**Issue by ljwwwiop** [zyc00/PartSLIP2#5]
Hello! PartSLip and PartSLip++ are indeed excellent pieces of research. I would like to know if the paper is currently under review? Additionally, I am interested in whether the evaluation code provided is consistent with the metrics mentioned in the paper? I am also conducting research on zero-shot part segmentation and I am looking to cite PartSLip and PartSLip++ for performance comparison and analysis. Ensuring the fairness of the comparison is very important to me. 
I look forward to your reply.

**Comment by ljwwwiop** [comment]
![image](https://github.com/zyc00/PartSLIP2/assets/45536607/3e57c415-c4aa-4026-a2dc-5c911341ef31)
l see that, maintaining the same setting as in PartSLip, it means to randomly select 8 shapes from each of the 45 categories, is that correct? Does this imply that there might be variability in the results each time due to the randomness? Moreover, it seems that for zero-shot, only 45*8 level test samples are needed for comparison, right?

**Comment by zyc00** [comment]
45 * 8 is used for few-shot fine-tuning, few-shot and zero-shot evaluation are both on the whole PartNet-Mobility, which is the test set of PartNet-E.

**Comment by ljwwwiop** [comment]
> 45 * 8 is used for few-shot fine-tuning, few-shot and zero-shot evaluation are both on the whole PartNet-Mobility, which is the test set of PartNet-E.

Thanks, I understand!
